"""empty message

Revision ID: 93aecc6cd94e
Revises: a0124c73540f
Create Date: 2018-03-02 22:12:20.559679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93aecc6cd94e'
down_revision = 'a0124c73540f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'password')
    # ### end Alembic commands ###
